steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/runtime-image-scanner:$TAG', '.']
  id: 'build-and-test'

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/runtime-image-scanner:$TAG']
  id: 'push'