steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/totvs-kubernetes-service/runtime-image-scanner:$TAG_NAME', '.']
  id: 'build-and-test'

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/totvs-kubernetes-service/runtime-image-scanner:$TAG_NAME']
  id: 'push'