steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['run', '--privileged', 'linuxkit/binfmt:v0.7']
  id: 'initialize-qemu'
- name: 'gcr.io/cloud-builders/docker'
  args: ['buildx', 'create', '--name', 'mybuilder']
  id: 'create-builder'
- name: 'gcr.io/cloud-builders/docker'
  args: ['buildx', 'use', 'mybuilder']
  id: 'select-builder'
- name: 'gcr.io/cloud-builders/docker'
  args: ['buildx', 'inspect', '--bootstrap']
  id: 'show-target-build-platforms'
- name: "gcr.io/cloud-builders/docker"
  args: ["buildx", "build", "--push", "--platform","linux/arm64,linux/amd64", "-t", "gcr.io/totvs-kubernetes-service/runtime-image-scanner:$TAG_NAME", "."]
  id: 'build'
