{
 "title": "Vulnerabilidades do Cluster",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Geral", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total de Vulnerabilidades por Severidade",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (Severity) (pod_security_issue > 0)",
     "legendFormat": "{{Severity}}"
    }
   ]
  },
  {
   "title": "Namespaces vs severidade",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum(pod_security_issue > 0) by (Namespace,Severity)",
     "legendFormat": "{{Namespace}}"
    }
   ]
  },
  {
   "title": "TOP Docker Images",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum(pod_security_issue > 0) by (Image,Severity)",
     "legendFormat": "CVE"
    }
   ]
  },
  {
   "title": "TOP CVE",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "sum(pod_security_issue > 0) by (VulnerabilityID,PkgName)",
     "legendFormat": "CVE"
    }
   ]
  },
  {
   "title": "TOP Pacotes",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "sum(pod_security_issue > 0) by (PkgName,InstalledVersion)",
     "legendFormat": "CVE"
    }
   ]
  },
  { "title": "Público", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Pods Públicas vs Severidade",
   "type": "grafana-piechart-panel",
   "description": "Pods \"embaixo\" de um ingress",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 38 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(pod_security_issue{IsPublic=\"True\"} > 0) by (Severity)",
     "legendFormat": "{{Severity}}"
    }
   ]
  },
  {
   "title": "Namespaces com recursos públicos  vs severidade",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "sum(pod_security_issue{IsPublic=\"True\"} > 0) by (Namespace,Severity)",
     "legendFormat": "{{Namespace}}"
    }
   ]
  },
  {
   "title": "TOP Docker Image",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 55 },
   "targets": [
    {
     "expr": "sum(pod_security_issue{IsPublic=\"True\"} > 0) by (Image,Severity)",
     "legendFormat": "CVE"
    }
   ]
  },
  {
   "title": "TOP CVE",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 63 },
   "targets": [
    {
     "expr": "sum(pod_security_issue{IsPublic=\"True\"} > 0) by (VulnerabilityID,PkgName)",
     "legendFormat": "CVE"
    }
   ]
  },
  {
   "title": "TOP Pacotes",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 63 },
   "targets": [
    {
     "expr": "sum(pod_security_issue{IsPublic=\"True\"} > 0) by (PkgName,InstalledVersion)",
     "legendFormat": "CVE"
    }
   ]
  }
 ]
}