{
 "title": "Vulnerabilidades especificas por namespace",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_pod_info, namespace)"
    }
   },
   {
    "name": "ispublic",
    "label": "Is Public?",
    "query": "label_values(pod_security_issue,IsPublic)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(pod_security_issue{Namespace=\"$namespace\",IsPublic=~\"$ispublic\"}, PodName)"
   },
   {
    "name": "image",
    "label": "Image",
    "query": "label_values(pod_security_issue{Namespace=\"$namespace\",PodName=~\"$pod\",IsPublic=~\"$ispublic\"}, Image)"
   },
   {
    "name": "baseos",
    "label": "Base OS",
    "query": {
     "query": "label_values(pod_security_issue{Namespace=\"$namespace\",PodName=~\"$pod\",Image=~\"$image\",IsPublic=~\"$ispublic\"},BaseOS)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Métricas Gerais", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Porcentagem de Famílias de SO",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(pod_security_issue{Namespace=\"$namespace\",PodName=~\"$pod\",Image=~\"$image\",IsPublic=~\"$ispublic\"}) by (BaseOS)",
     "legendFormat": "{{BaseOS}}"
    }
   ]
  },
  {
   "title": "Severidade",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (pod_security_issue{Namespace=\"$namespace\",PodName=~\"$pod\",Image=~\"$image\",IsPublic=~\"$ispublic\",BaseOS=~\"$baseos\"} > 0) by (Severity)",
     "legendFormat": "{{Severity}}"
    }
   ]
  },
  {
   "title": "TOP Pacote",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(pod_security_issue{Namespace=\"$namespace\",PodName=~\"$pod\",Image=~\"$image\",IsPublic=~\"$ispublic\",BaseOS=~\"$baseos\"} > 0) by (PkgName,Severity,InstalledVersion,FixedVersion)",
     "legendFormat": "CVE"
    }
   ]
  },
  { "title": "Especificas por Severidade", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Pacotes instalados com severidade \"LOW\"",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 18 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (pod_security_issue{Namespace=\"$namespace\", Severity=\"LOW\",PodName=~\"$pod\",Image=~\"$image\",IsPublic=~\"$ispublic\",BaseOS=~\"$baseos\"}) by (PkgName)",
     "legendFormat": "{{PkgName}}"
    }
   ]
  },
  {
   "title": "Pacotes instalados com severidade \"MEDIUM\"",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 18 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (pod_security_issue{Namespace=\"$namespace\", Severity=\"MEDIUM\",PodName=~\"$pod\",Image=~\"$image\",IsPublic=~\"$ispublic\",BaseOS=~\"$baseos\"}) by (PkgName)",
     "legendFormat": "{{PkgName}}"
    }
   ]
  },
  {
   "title": "Pacotes instalados com severidade \"HIGH\"",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 18 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (pod_security_issue{Namespace=\"$namespace\", Severity=\"HIGH\",PodName=~\"$pod\",Image=~\"$image\",IsPublic=~\"$ispublic\",BaseOS=~\"$baseos\"}) by (PkgName)",
     "legendFormat": "{{PkgName}}"
    }
   ]
  },
  {
   "title": "Pacotes instalados com severidade \"UNKNOWN\"",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 18 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (pod_security_issue{Namespace=\"$namespace\", Severity=\"UNKNOWN\",PodName=~\"$pod\",Image=~\"$image\",IsPublic=~\"$ispublic\",BaseOS=~\"$baseos\"}) by (PkgName)",
     "legendFormat": "{{PkgName}}"
    }
   ]
  },
  {
   "title": "TOP CVE",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum(pod_security_issue{Namespace=\"$namespace\",PodName=~\"$pod\",Image=~\"$image\",IsPublic=~\"$ispublic\",BaseOS=~\"$baseos\"} > 0) by (VulnerabilityID,Severity)",
     "legendFormat": "CVE"
    }
   ]
  },
  {
   "title": "TOP Docker Image",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "sum(pod_security_issue{Namespace=\"$namespace\",IsPublic=~\"$ispublic\",BaseOS=~\"$baseos\"} > 0) by (Image,Severity)",
     "legendFormat": "CVE"
    }
   ]
  }
 ]
}