apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: image-scanner
    prometheus: tks
  name: image-scanner
  namespace: tks-system
spec:
  endpoints:
  - port: http
  jobLabel: image-scanner
  namespaceSelector:
    matchNames:
    - tks-system
  selector:
    matchLabels:
      app: image-scanner
