apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name | trunc 63  }}
  labels:
{{ include "runtime-image-scanner.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "runtime-image-scanner.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "runtime-image-scanner.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ template "runtime-image-scanner.serviceAccountName" . }}
      terminationGracePeriodSeconds: 5
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.volume.create }}
          volumeMounts:
          - mountPath: {{ .Values.volume.mountPath }}
            name: persistent-data
          {{- end }}
          {{- if .Values.Envs }}
          env:
            {{- toYaml .Values.Envs | nindent 12 }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- if .Values.volume.create }}
      volumes:
        - name: persistent-data
          persistentVolumeClaim:
            claimName: {{ .Release.Name | trunc 63  }}
    {{- end }}