{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "runtime-image-scanner.serviceAccountName" . }}
  labels:
{{ include "runtime-image-scanner.labels" . | indent 4 }}
{{- end -}}
