apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name | trunc 63  }}
  labels:
{{ include "runtime-image-scanner.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  selector:
      app.kubernetes.io/name: {{ include "runtime-image-scanner.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
